/*
 * RTE_Components.h
 * CMSIS Component Configuration File
 * Generated by CMSIS Project Manager
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Component: ARM::CMSIS
 */
#define CMSIS_device_header "ARMCA53.h"

#endif /* RTE_COMPONENTS_H */